### ISSUE TITLE
How can  i use the gimp python_script

### ISSUE THREAD

**Issue by Haosouth** [eib/gimp-plugins#2]
Hello, I'm also trying to write a python plug-in for gimp, but I don't know the process. I already have the code, but I don't know how to turn it into a gimp plug-in. I've read your plug-in, but I don't know how to use it. Do you have any related references

**Comment by eib** [comment]
Interesting that you found my repo first. 😄 

It's been a while since I worked on any plugins, but here's some of my bookmarks:

* [GIMP-Python docs](https://www.gimp.org/docs/python/index.html)
* [libgimp 2.0 API](https://developer.gimp.org/api/2.0/libgimp/libgimp-image.html)
* [GIMP PDB docs](http://oldhome.schmorp.de/marc/pdb/index.html)

**Comment by eib** [comment]
(Will close this request for help.)
